name: Tackle Controls Issues Sync

defaults:
  run:
    shell: bash
    working-directory: src/main/resources/

on:
  issues:
    types: [opened, closed, reopened]

jobs:

  sync-opened:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' && startsWith(github.event.issue.title, '[TACKLE-') }}
    name: New GitHub Issue to sync with Jira
    steps:
      - uses: actions/checkout@v2.1.0
      - env:
          BEARER: ${{ secrets.JIRA_TACKLE_BEARER }}
          JIRA_ISSUE_ID: echo ${{ github.event.issue.title }}|cut -d] -f1|sed 's/[[]//g'
          TITLE: echo ${{ github.event.issue.title }}|cut -d] -f2
          NUMBER: ${{ github.event.issue.number }}
          DESCRIPTION: ${{ github.event.issue.html_url }}
        run: |
          echo $JIRA_ISSUE_ID
          echo $TITLE
          echo $NUMBER
          echo $DESCRIPTION
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer "$BEARER https://issues.redhat.com/rest/api/2/issue/ -d "{ \"fields\": { \"project\": { \"key\": \"TACKLE\" }, \"parent\": { \"key\": \"$JIRA_ISSUE_ID\" }, \"summary\": \"[tackle-controls#$NUMBER]$TITLE\", \"description\": \"$DESCRIPTION\", \"issuetype\": { \"id\": 5 } } }"

  sync-reopened:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'reopened' && startsWith(github.event.issue.title, '[TACKLE-') }}
    name: Reopened GitHub Issue to sync with Jira
    steps:
      - env:
          BEARER: ${{ secrets.JIRA_TACKLE_BEARER }}
          JIRA_ISSUE_ID: echo ${{ github.event.issue.title }}|cut -d] -f1|sed 's/[[]//g'
          NUMBER: ${{ github.event.issue.number }}
        run: |
          src/main/resources/issue_transaction.sh 4

  sync-closed:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' && startsWith(github.event.issue.title, '[TACKLE-') }}
    name: Closed GitHub Issue to sync with Jira
    steps:
      - env:
          BEARER: ${{ secrets.JIRA_TACKLE_BEARER }}
          JIRA_ISSUE_ID: echo ${{ github.event.issue.title }}|cut -d] -f1|sed 's/[[]//g'
          NUMBER: ${{ github.event.issue.number }}
        run: |
          src/main/resources/issue_transaction.sh 2
